### ISSUE TITLE
[BUG] Version 2.0.0 breaks py3Dmol

### ISSUE THREAD

**Issue by accelyte** [3dmol/3Dmol.js#635]
**Describe the bug**
See title.

**To Reproduce**
1. Go to "Jupyter" on https://3dmol.csb.pitt.edu/index.html
2. Run the first three cells
3. See that there is no output

**Expected behavior**
There should be an interactive 3D render.

**Screenshots**
![image](https://user-images.githubusercontent.com/95587932/210611439-68a02e0c-7361-450e-b403-09038c5619c0.png)

**Comment by TaoDFang** [comment]
It seems i also get this problem. 1 day or two day2 ago I could see output figure . 
while today I didnt change anything but same jupyter notebook script . The output figure went blank .

**Comment by accelyte** [comment]
My temporary solution is to force py3Dmol to use the old version:
`viewer = py3Dmol.view(js="https://cdn.jsdelivr.net/npm/3dmol@1.8.0/build/3Dmol-min.min.js")`

Hopefully that helps for now.

**Comment by TaoDFang** [comment]
> My temporary solution is to force py3Dmol to use the old version: `viewer = py3Dmol.view(js="https://cdn.jsdelivr.net/npm/3dmol@1.8.0/build/3Dmol-min.min.js")`
> 
> Hopefully that helps for now.

thanks for helping 
i run code 
```
print(py3Dmol.__version__) ## 1.8.1 
p = py3Dmol.view(query='mmtf:1ycr',js="https://cdn.jsdelivr.net/npm/3dmol@1.8.0/build/3Dmol-min.min.js")
p.setStyle({'cartoon': {'color':'spectrum'}})
p
```

on "jupyter" at https://3dmol.csb.pitt.edu/index.html. it works !
but when i run it on my local jupyter notebook. It fails again with blank output 

maybe it also depend on jupyter version ?
I run "!jupyter --version"  on "jupyter" at https://3dmol.csb.pitt.edu/index.html. get 
Selected Jupyter core packages...
```
IPython          : 7.9.0
ipykernel        : 5.3.4
ipywidgets       : 7.7.1
jupyter_client   : 6.1.12
jupyter_core     : 5.1.1
jupyter_server   : not installed
jupyterlab       : not installed
nbclient         : not installed
nbconvert        : 5.6.1
nbformat         : 5.7.1
notebook         : 5.7.16
qtconsole        : not installed
traitlets        : 5.7.1
```

on my own local jupyter notebook , get : 
```
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : 5.1.1
ipython          : 7.25.0
ipykernel        : 5.3.4
jupyter client   : 6.1.12
jupyter lab      : 3.2.9
nbconvert        : 6.1.0
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
```

**Comment by accelyte** [comment]
On Chrome, if you right click -> `Inspect` to go to the DevTools, and open the `Sources` tab, you can actually double check which version the notebook cell is using. On the Google Colab version: 
![image](https://user-images.githubusercontent.com/95587932/210621764-4c5c3de1-2c84-4054-a176-ab66cc71fbb0.png)

You should be able to find a similar tab for your local notebook. When I was testing my workaround, I found that Chrome seems to temporarily cache the notebook cell output, which contains the Javascript URL pointing to `latest`. You can try restarting Jupyter notebook a couple times (i.e. close the tabs, restart Jupyter notebook, reopen the notebook) and see whether the cells get updated correctly.

**Comment by pablo-arantes** [comment]
I'm having the same error. I've tried the temporary solution, and it works well for me. I'm using on Google Colab.

**Comment by dkoes** [comment]
Sorry about that - I thought I had verified that py3Dmol worked fine with the new 2.0 3Dmol.js release, but obviously I failed.  It should be working now as long as you are getting `py3Dmol-2.0.0.post1` when you pip install.  

Please verify and close the issue.

**Comment by TaoDFang** [comment]
> 

brilliant . Chrome indeed cache the javascript URL. 
after i restarted my jupyter notebook, problem solved. 
Thank you !

**Comment by TaoDFang** [comment]
> On Chrome, if you right click -> `Inspect` to go to the DevTools, and open the `Sources` tab, you can actually double check which version the notebook cell is using. On the Google Colab version: ![image](https://user-images.githubusercontent.com/95587932/210621764-4c5c3de1-2c84-4054-a176-ab66cc71fbb0.png)
> 
> You should be able to find a similar tab for your local notebook. When I was testing my workaround, I found that Chrome seems to temporarily cache the notebook cell output, which contains the Javascript URL pointing to `latest`. You can try restarting Jupyter notebook a couple times (i.e. close the tabs, restart Jupyter notebook, reopen the notebook and rerun the cells) and see whether the cells get updated correctly.

brilliant . Chrome indeed cache the javascript URL.
after i restarted my jupyter notebook, problem solved.
Thank you !

**Comment by accelyte** [comment]
@dkoes I installed py3Dmol using conda (`conda install -c conda-forge py3Dmol`), so I temporarily replaced `__init__.py` to simulate using the new version. However, I'm still getting errors:
![image](https://user-images.githubusercontent.com/95587932/210643690-43ac6ae0-7f3c-4800-ab93-3aa69355048e.png)
![image](https://user-images.githubusercontent.com/95587932/210643785-9482cab1-64c8-43f9-b2d4-1488729e2ca8.png)

**Comment by dkoes** [comment]
I'm not sure what could be wrong.   Did you try clearing your browser cache?  Uninstalling with conda and then installing with pip? If you can post a malfunctioning notebook I can see if it works for me.

**Comment by accelyte** [comment]
Here's what I did:
1. Create a new conda environment with Jupyter notebook installed: `conda create -n py3dmol-test notebook`
2. In the activated environment, install py3Dmol using pip: `pip install py3Dmol`. See that `2.0.0.post1` is installed.
3. Launch the notebook in a completely different browser (Microsoft Edge, not Chrome)
4. See the error as shown above.

The notebook (I doubt it will be of any use): [Untitled.zip](https://github.com/3dmol/3Dmol.js/files/10347462/Untitled.zip)

**Comment by dkoes** [comment]
Okay, I think I've figured it out.  It was an issue with requirejs/AMD module loading which apparently doesn't matter for colab?  Try again with `2.0.0.post2`
